## **NUMPY BASICS #3**

This NumPy notebook covers
>   - NumPy Mathematics
>   - NumPy Linear Algebra
>   - NumPy Statistics
>   - NumPy 

In [2]:
import numpy as np

#### **NumPy Mathematics** <br>
>   -   refer to numpy mathematics documentation at - `https://numpy.org/doc/stable/reference/routines.math.html`
>   -   Explore and play with the functions that are not shown in notebook

In [13]:
# scalar operations on numpy arrays
a = np.arange(6)

print(a+2)
print(a-3)
print(a*2)
print(a/2)

[2 3 4 5 6 7]
[-3 -2 -1  0  1  2]
[ 0  2  4  6  8 10]
[0.  0.5 1.  1.5 2.  2.5]
