## **NUMPY BASICS #3**

This NumPy notebook covers
>   - NumPy Mathematics
>   - NumPy Linear Algebra
>   - NumPy Statistics
>   - NumPy 

In [ ]:
import numpy as np

#### **NumPy Axis**
<pre>
            axis=0
                |
                |
                |_______ axis =1
</pre>

#### **NumPy Mathematics** <br>
>   -   refer to numpy mathematics documentation at - `https://numpy.org/doc/stable/reference/routines.math.html`
>   -   Explore and play with the functions that are not shown in notebook

In [ ]:
# scalar operations on numpy arrays
a = np.arange(6)

print(a+2)
print(a-3)
print(a*2)
print(a/2)

**math functions in Numpy** <br>_few examples_
>   -   `add(), subtract(), multiply(), divide()`
>   -   `sum()`
>   -   `prod()`
>   -   `sin()`
>   -   `cos()`

In [ ]:
# math opearations on two arrays
a = np.arange(1,6,2)
b = np.arange(6,12,2)

print(a+b)   # adding two numpy array
print(np.add(a,b))   # same as a+b
print(b-a)   # difference of two arrays
print(np.subtract(b,a))   # same as b-a
print(a*b)   # multiplication of two arrays
print(np.multiply(a,b))  # same as a*b
print(b/a)   # division of two arrays
print(np.divide(b,a)) # same as b/a


In [ ]:
m_array = np.arange(6).reshape(2,3)

print(m_array)
print(np.sum(m_array))    # sum()
print(np.prod(m_array, axis=0))  #prod

In [ ]:
arr = np.array([1,3,6])
print(np.sin(arr))
print(np.cos(arr))


#### **NumPy Linear Algebra Functions** <br>
>   -   refer to numpy linear algebra documentation at - `https://numpy.org/doc/stable/reference/routines.linalg.html`
>   -   Explore and play with the functions that are not shown in notebook

**trace()**
>   trace - sum along diagonals


In [ ]:

print(np.eye(3))
print(np.trace(np.arange(9).reshape(3,3)))

print(np.trace(np.arange(8).reshape(2,2,2)))
np.arange(8).reshape(2,2,2)

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)


**dot()**
>   -   multiplication of two matrices
>   -   multiplication by scalars are allowed

In [ ]:
np.dot(a,b)
np.dot(b,a)

print(np.dot(a,3))

**dot()**

In [ ]:
np.dot(3,4)

In [ ]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

np.dot(a,2)

**matmul()**
>   -   Matrix product of two arrays
>   -   Scalar products are not allowed

>   -   **CASE** - both arguments are 2d-arrays
>   -   both arrays are multiplied like dot product (`matrix multiplication`)

In [ ]:
a = np.ones((2,2))
b = np.eye(2)
print(np.matmul(a,b) )  
np.matmul(b,a)

>   -   **CASE** - one arguments are 2d-array and another is 1d-array
>   -   If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
>   -   If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.


```

        When -First argument 2d (2,2) , (1,2) -> (1,2)  
        When -Second argument 2d  (1,2) , (2,2) -> (1,2)
```

In [ ]:

a = np.ones((2,2))
b = np.array([1,3])

# 2d & 1d-arrays
np.matmul(a,b)

# 1d & 2d-arrays
np.matmul(b,a)

In [ ]:
a = np.ones((2,2))
b = np.array([2,3])

print(np.matmul(a,b) )  
np.matmul(b,a)

>   -   **CASE** - any arguments are Nd-array where N>2
>   -   treated as stack of matrices residing in the last two indexes and then broadcast


```

        First argument 4d (4,6,1,2)    
        Second argument 4d (4,6,2,1) 
        Result          4d (4,6,1,1)
```
rightmost 2 dimensions multiply following the rule `(n,k),(k,m)->(n,m)`  giving 1 x 1 matrix , others are broadcasted accordingly giving (4,6,1,1) shape

In [ ]:
a = np.ones([4,6,1,2])
b = np.ones([4,6,2,1])

np.matmul(a,b).shape

In [ ]:
np.matmul(b,a).shape

>   below example gives error as the left most dimensions after the 2 right most dimesions are not [broadcastable](./numpy_fundamentals_broadcasting.ipynb)

In [ ]:
c = np.ones([3,5,3,2])
d = np.ones([4,5,2,3])

np.matmul(c,d)

**matmul() vs dot()**
>   -   scalar multiplication not allowed in matmul 
>   -   Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature `(n,k),(k,m)->(n,m)`

_see notebook [`numpy_fundamentals_broadcasting`](./numpy_fundamentals_broadcasting.ipynb) for broadcasting_

In [ ]:
# matmul() - multiplication of two matrices , which are not scalars
np.matmul(a,b)

In [ ]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])

print(np.dot(a,c).shape)
np.matmul(a,c).shape

#### **NumPy Statistics Functions** <br>
>   -   refer to numpy statistics documentation at - `https://numpy.org/doc/stable/reference/routines.statistics.html`
>   -   Explore and play with the functions that are not shown in notebook


In [ ]:
a = np.array([[1,3,5],[2,4,6]])


In [10]:
#min
np.min(a)
np.min(a, axis=0)
np.min(a, axis=1)

array([1, 2])

In [13]:
#max
np.max(a)
np.max(a, axis=0)
np.max(a, axis=1)

array([5, 6])

In [16]:
#sum
np.sum(a)
np.sum(a,axis=0)
np.sum(a, axis=1)

array([ 9, 12])