#### **Lists v/s NumPy** <br>
Why is NumPy faster than Lists

1. NumPy arrays are of fixed types and uses a lot less space on disk than list
  lists uses built in data type in python to store data, and stores a lot more information than Numpy like <br>
  >    - size of element
  >    - reference count of element
  >    - Object type
  >    - Object Value


2. NumPy does not need to store all these additional data, binary form of Numpy uses a lot less space and much faster to read<br>
3. NumPy does not do type checking while iterating over elements, while lists have to do type checking, as there can be multiple data types in single list

4.  Contiguous memory allocation in NumPy
  > - Benefits
  >   -  SIMD (Single Instruction Multiple Data)  Vector Processing : all the elements are contigous, CPUs can perform operations on all elements in single instruction]
  >   -  Effective Utilization of Cache

5. **Operations**
    1. > Lists - insertion, deletion, append, concat etc
    2. > NumPy - all list operations , plus much more , eg like multiply [a*b] , not possible in lists and many other mathematical operations


In [3]:
# this will give error
a = [1,2,3]
b = [3,4,5]
c = a*b
print(c)

In [2]:
#import numpy statement
import pandas as pd
import numpy as np

In [4]:
#valid operation in NumPy
a = np.array([1,3,5])
b = np.array([1,2,3])
print(a*b)

[ 1  6 15]


### *First Step* <br>
Create Numpy Array

In [3]:
a = np.array([1,2,3])

In [7]:
#create two dimensional array
twod_array= np.array([[1,2,3,4],[5,6,7,8]])
print(twod_array)

[[1 2 3 4]
 [5 6 7 8]]


### *Dimension & Size of Numpy Array*

In [14]:
#get dimension of numpy array
a.ndim
print(twod_array.ndim)
#get type of array
# int32 is default , but you can create with a different dtype if you'd want to be more efficient ( eg shown)
a.dtype
b = np.array([1,3,6], dtype='int16')
print(b.dtype)


2
int16


In [19]:
#NumPy size attributes

a.size   # number of elements in array
a.itemsize   # size of each elemets in bytes
a.nbytes   # total size of array in bytes  [ a.size * a.itemsize ]

12

In [22]:
# some more example of size
print(twod_array.size)
print(twod_array.itemsize)
print(twod_array.nbytes)

8
4
32
